# fly.toml app configuration file generated for bankapp-winter-water-3545 on 2025-02-25T16:06:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[build]
  builder = 'paketobuildpacks/builder:base'
  buildpacks = ['gcr.io/paketo-buildpacks/java']

[env]
  JAVA_VERSION = '21'
  SPRING_PROFILES_ACTIVE = 'prod'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
