# lifehack, you can use this file to have a dev version of the app running
# here you can use different env variables
# then you can run the app with that parameter to have it running with dev profile
# -Dspring.profiles.active=dev
# Server configuration
server:
  address: 0.0.0.0
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict #if there will be problems with password reset or registration then change it to `lex`

# Application variables
spring:
  # Spring Security
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_SCHEMA:bankapp}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # Connection pool settings
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
  # JPA / Hibernate settings
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[show_sql]': false
        '[format_sql]': true
        '[globally_quoted_identifiers]': true
        jdbc:
          lob:
            non_contextual_creation: true
  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0
    placeholder-replacement: true
    placeholders:
      bank_password: ${BANK_PASSWORD:password}

# Swagger / OpenAPI configuration
springdoc:
  swagger-ui:
    docExpansion: list
  default-produces-media-type: application/json
  show-actuator: false
  model-and-view-allowed: true

app:
  # Email configuration
  ## Resend API configuration
  resend:
    api-key: ${RESEND_API_KEY}
  ## Application base URL (for generating links in emails)
  base-url: ${APP_BASE_URL:http://localhost:8080}
  ## Frontend configuration
  thymeleaf:
    enabled: ${THYMELEAF_ENABLED:true}
  ## Account locking configuration
  locking:
    max-attempts: 5
    base-delay: 100
    max-delay: 2000
    timeout: 200

bankapp:
  registration:
    WelcomeBonusAmount: 1000
  bank:
    account:
      iban: PL66485112340000000000000000
  restrictions:
    MaxAccountsPerUser: ${MAX_ACCOUNTS_PER_USER:3}


  # Logging configuration
logging:
  stacktrace:
    enabled: false
#     level:
#         root: INFO
#         info:
#             mackiewicz:
#                 bankapp: DEBUG
#     file:
#         name: logs/app.log
#     pattern:
#         file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
#         console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'