CREATE TABLE IF NOT EXISTS users (
  id                  SERIAL PRIMARY KEY,
  credentials_expired BOOLEAN NOT NULL,
  enabled             BOOLEAN NOT NULL,
  expired             BOOLEAN NOT NULL,
  locked              BOOLEAN NOT NULL,
  password            VARCHAR(255),
  username            VARCHAR(255) NOT NULL,
  account_counter     INTEGER,
  date_of_birth       DATE NOT NULL,
  email               VARCHAR(255) NOT NULL,
  firstname           VARCHAR(255) NOT NULL,
  lastname            VARCHAR(255) NOT NULL,
  pesel               VARCHAR(255) NOT NULL,
  phone_number        VARCHAR(255) NOT NULL,
  CONSTRAINT uk_users_username       UNIQUE (username),
  CONSTRAINT uk_users_email          UNIQUE (email),
  CONSTRAINT uk_users_pesel          UNIQUE (pesel),
  CONSTRAINT uk_users_phone_number   UNIQUE (phone_number)
);